name: mobileprogramming
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.0.0+18

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.4.0
  firebase_storage: ^12.3.7
  # fluttertoast: ^8.2.10
  file_picker: ^8.1.7
  image_picker: ^1.1.2
  intl: ^0.20.1
  uuid: ^4.5.1
  # sizer: ^3.0.0
  google_fonts: ^6.2.1
 
  sizer: ^3.0.0
  flutter_sizer: ^1.0.5
  rename_app: ^1.6.1
  google_sign_in: ^6.2.2
  firebase_app_check: ^0.3.1+7
  shared_preferences: ^2.3.5
  animations: ^2.0.11
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  table_calendar: ^3.2.0
  # sqflite: ^2.4.1
    # sqflite: ^2.4.1
  path: ^1.8.0
  sqflite: ^2.4.1
  lottie: ^3.2.0
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.8.3
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.2.0
  path_provider: ^2.1.5
  permission_handler: ^11.2.0
  # file_picker: ^8.1.5
  # file_picker: ^8.1.5
  url_launcher: ^6.1.7
  fl_chart: ^0.70.2
  flutter_svg: ^2.0.17
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/welcome.png
    - assets/reading.png
    - assets/slide1.png
    - assets/slide2.png
    - assets/slide3.png
    - assets/slide4.png
    - assets/userImage.png
    - assets/webInterFace.png
    - assets/submit-assignment.jpg
    - assets/introduction_animation/care_image.png
    - assets/introduction_animation/introduction_image.png
    - assets/introduction_animation/benefits.png
    - assets/introduction_animation/features.png
    - assets/introduction_animation/welcome.png
    - assets/CourseDesign/interFace1.png
    - assets/CourseDesign/interFace2.png
    - assets/CourseDesign/interFace3.png
    - assets/CourseDesign/interFace4.png
    - assets/CourseDesign/webInterFace.png
    - .env
