import 'package:flutter/material.dart';
import 'package:mobileprogramming/models/assignment_model.dart';
import 'package:mobileprogramming/services/AssignmentService.dart';
class CreateAssignmentScreen extends StatelessWidget {
  final String courseId;
  final String userId;

  CreateAssignmentScreen({super.key, required this.courseId, required this.userId});

  final TextEditingController titleController = TextEditingController();
  final TextEditingController descriptionController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Create Assignment'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            TextField(
              controller: titleController,
              decoration: InputDecoration(labelText: 'Title'),
            ),
            TextField(
              controller: descriptionController,
              decoration: InputDecoration(labelText: 'Description'),
            ),
            SizedBox(height: 20),
            ElevatedButton(
              onPressed: () async {
                final assignment = Assignment(
                  id: '', // Generated by backend
                  title: titleController.text,
                  description: descriptionController.text,
                  courseId: courseId,
                  createdBy: userId,
                );
                await ApiService(baseUrl: 'http://example.com', userId: userId)
                    .createAssignment(assignment);
                if(!context.mounted) return;
                Navigator.pop(context);
              },
              child: Text('Create'),
            ),
          ],
        ),
      ),
    );
  }
}
